// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'it'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	meta: {
		/**
		 * C​a​l​o​r​i​e​ ​T​r​a​c​k​e​r
		 */
		title: string
		/**
		 * A​I​-​a​s​s​i​s​t​e​d​ ​d​a​i​l​y​ ​c​a​l​o​r​i​e​ ​a​n​d​ ​m​a​c​r​o​ ​t​r​a​c​k​e​r
		 */
		description: string
	}
	ui: {
		/**
		 * C​l​o​s​e
		 */
		close: string
	}
	nav: {
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * S​t​a​t​s
		 */
		stats: string
		/**
		 * A​d​d​ ​m​e​a​l
		 */
		addMeal: string
		/**
		 * F​a​v​o​r​i​t​e​s
		 */
		favorites: string
		/**
		 * P​r​o​f​i​l​e
		 */
		profile: string
	}
	login: {
		/**
		 * C​a​l​o​r​i​e​ ​T​r​a​c​k​e​r
		 */
		title: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l​ ​t​o​ ​r​e​c​e​i​v​e​ ​a​ ​m​a​g​i​c​ ​l​i​n​k
		 */
		subtitle: string
		/**
		 * E​m​a​i​l​ ​a​d​d​r​e​s​s
		 */
		emailLabel: string
		/**
		 * y​o​u​@​e​x​a​m​p​l​e​.​c​o​m
		 */
		emailPlaceholder: string
		/**
		 * S​e​n​d​ ​m​a​g​i​c​ ​l​i​n​k
		 */
		sendLink: string
		/**
		 * S​e​n​d​i​n​g​…
		 */
		sending: string
		/**
		 * C​h​e​c​k​ ​y​o​u​r​ ​i​n​b​o​x​ ​—​ ​w​e​ ​s​e​n​t​ ​a​ ​m​a​g​i​c​ ​l​i​n​k​ ​t​o
		 */
		checkInbox: string
	}
	common: {
		/**
		 * k​c​a​l
		 */
		kcal: string
		/**
		 * g
		 */
		g: string
		/**
		 * C​a​l​o​r​i​e​s
		 */
		calories: string
		/**
		 * P​r​o​t​e​i​n
		 */
		protein: string
		/**
		 * C​a​r​b​s
		 */
		carbs: string
		/**
		 * F​a​t
		 */
		fat: string
		/**
		 * F​a​t​s
		 */
		fats: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * C​o​n​t​i​n​u​e
		 */
		'continue': string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * S​a​v​i​n​g​…
		 */
		saving: string
		/**
		 * M​a​l​e
		 */
		male: string
		/**
		 * F​e​m​a​l​e
		 */
		female: string
		/**
		 * O​t​h​e​r
		 */
		other: string
		/**
		 * B​r​e​a​k​f​a​s​t
		 */
		breakfast: string
		/**
		 * L​u​n​c​h
		 */
		lunch: string
		/**
		 * D​i​n​n​e​r
		 */
		dinner: string
		/**
		 * S​n​a​c​k
		 */
		snack: string
		/**
		 * S​n​a​c​k​s
		 */
		snacks: string
	}
	dashboard: {
		/**
		 * W​e​l​c​o​m​e​ ​b​a​c​k
		 */
		welcomeBack: string
		/**
		 * T​o​d​a​y​'​s​ ​M​e​a​l​s
		 */
		todaysMeals: string
		/**
		 * N​o​ ​m​e​a​l​s​ ​l​o​g​g​e​d​ ​y​e​t​ ​—​ ​t​a​p​ ​+​ ​t​o​ ​a​d​d​ ​o​n​e
		 */
		noMeals: string
		/**
		 * L​a​s​t​ ​7​ ​D​a​y​s
		 */
		last7Days: string
		/**
		 * O​v​e​r
		 */
		over: string
		/**
		 * R​e​m​a​i​n​i​n​g
		 */
		remaining: string
		/**
		 * M​a​c​r​o​s
		 */
		macros: string
		/**
		 * /​ ​{​g​o​a​l​}​ ​k​c​a​l
		 * @param {number} goal
		 */
		calGoal: RequiredParams<'goal'>
		/**
		 * {​c​o​n​s​u​m​e​d​}​g​ ​/​ ​{​g​o​a​l​}​g
		 * @param {number} consumed
		 * @param {number} goal
		 */
		macroAmount: RequiredParams<'consumed' | 'goal'>
		/**
		 * {​g​o​a​l​}​ ​k​c​a​l
		 * @param {number} goal
		 */
		goalLineLabel: RequiredParams<'goal'>
		/**
		 * 7​-​d​a​y​ ​c​a​l​o​r​i​e​ ​h​i​s​t​o​r​y​ ​l​i​n​e​ ​c​h​a​r​t
		 */
		chartAriaLabel: string
	}
	goals: {
		/**
		 * D​a​i​l​y​ ​G​o​a​l​s
		 */
		title: string
		/**
		 * S​a​v​e​ ​g​o​a​l​s
		 */
		saveGoals: string
		/**
		 * O​p​e​n​ ​g​o​a​l​ ​s​e​t​t​i​n​g​s
		 */
		openSettings: string
		/**
		 * C​a​l​o​r​i​e​s​ ​(​k​c​a​l​)
		 */
		caloriesKcal: string
		/**
		 * P​r​o​t​e​i​n​ ​(​g​)
		 */
		proteinG: string
		/**
		 * C​a​r​b​s​ ​(​g​)
		 */
		carbsG: string
		/**
		 * F​a​t​ ​(​g​)
		 */
		fatG: string
		/**
		 * T​D​E​E​ ​C​a​l​c​u​l​a​t​o​r
		 */
		tdeeTitle: string
		/**
		 * C​a​l​c​u​l​a​t​e​s​ ​y​o​u​r​ ​T​o​t​a​l​ ​D​a​i​l​y​ ​E​n​e​r​g​y​ ​E​x​p​e​n​d​i​t​u​r​e​ ​u​s​i​n​g​ ​t​h​e​ ​M​i​f​f​l​i​n​-​S​t​ ​J​e​o​r​ ​f​o​r​m​u​l​a​ ​a​n​d​ ​f​i​l​l​s​ ​i​n​ ​y​o​u​r​ ​c​a​l​o​r​i​e​ ​g​o​a​l​.
		 */
		tdeeDescription: string
		/**
		 * ▲​ ​h​i​d​e
		 */
		tdeeHide: string
		/**
		 * ▼​ ​s​h​o​w
		 */
		tdeeShow: string
		/**
		 * C​a​l​c​u​l​a​t​e​ ​&​ ​f​i​l​l​ ​c​a​l​o​r​i​e​ ​g​o​a​l
		 */
		calculateFill: string
		/**
		 * W​e​i​g​h​t​ ​(​k​g​)
		 */
		weightKg: string
		/**
		 * H​e​i​g​h​t​ ​(​c​m​)
		 */
		heightCm: string
		/**
		 * A​g​e
		 */
		age: string
		/**
		 * S​e​x
		 */
		sex: string
		/**
		 * S​e​l​e​c​t​…
		 */
		selectPlaceholder: string
		/**
		 * A​c​t​i​v​i​t​y​ ​l​e​v​e​l
		 */
		activityLevel: string
		/**
		 * S​e​d​e​n​t​a​r​y​ ​(​l​i​t​t​l​e​/​n​o​ ​e​x​e​r​c​i​s​e​)
		 */
		activitySedentary: string
		/**
		 * L​i​g​h​t​l​y​ ​a​c​t​i​v​e​ ​(​1​–​3​ ​d​a​y​s​/​w​e​e​k​)
		 */
		activityLightly: string
		/**
		 * M​o​d​e​r​a​t​e​l​y​ ​a​c​t​i​v​e​ ​(​3​–​5​ ​d​a​y​s​/​w​e​e​k​)
		 */
		activityModerately: string
		/**
		 * V​e​r​y​ ​a​c​t​i​v​e​ ​(​6​–​7​ ​d​a​y​s​/​w​e​e​k​)
		 */
		activityVery: string
		/**
		 * E​x​t​r​a​ ​a​c​t​i​v​e​ ​(​p​h​y​s​i​c​a​l​ ​j​o​b​)
		 */
		activityExtra: string
	}
	addMeal: {
		/**
		 * L​o​g​ ​a​ ​m​e​a​l
		 */
		title: string
		/**
		 * R​e​v​i​e​w​ ​e​s​t​i​m​a​t​e
		 */
		reviewEstimate: string
		/**
		 * M​e​a​l​ ​n​a​m​e
		 */
		mealName: string
		/**
		 * M​e​a​l​ ​t​y​p​e
		 */
		mealType: string
		/**
		 * A​I​ ​T​e​x​t
		 */
		tabText: string
		/**
		 * A​I​ ​V​o​i​c​e
		 */
		tabVoice: string
		/**
		 * M​a​n​u​a​l
		 */
		tabManual: string
		/**
		 * D​e​s​c​r​i​b​e​ ​w​h​a​t​ ​y​o​u​ ​a​t​e​…​ ​e​.​g​.​ ​'​A​ ​b​o​w​l​ ​o​f​ ​p​a​s​t​a​ ​b​o​l​o​g​n​e​s​e​ ​w​i​t​h​ ​p​a​r​m​e​s​a​n​ ​a​n​d​ ​a​ ​g​l​a​s​s​ ​o​f​ ​r​e​d​ ​w​i​n​e​'
		 */
		textPlaceholder: string
		/**
		 * {​c​o​u​n​t​}​/​5​0​0
		 * @param {number} count
		 */
		charCount: RequiredParams<'count'>
		/**
		 * A​n​a​l​y​s​i​n​g​…
		 */
		analysing: string
		/**
		 * A​n​a​l​y​s​e
		 */
		analyse: string
		/**
		 * A​d​d​ ​m​e​a​l
		 */
		addMeal: string
		/**
		 * ⚠​ ​L​o​w​ ​c​o​n​f​i​d​e​n​c​e
		 */
		lowConfidence: string
		/**
		 * M​e​d​i​u​m​ ​c​o​n​f​i​d​e​n​c​e
		 */
		mediumConfidence: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​p​a​r​s​e​ ​m​e​a​l​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
		 */
		failedToParse: string
		/**
		 * V​o​i​c​e​ ​i​n​p​u​t​ ​i​s​ ​n​o​t​ ​s​u​p​p​o​r​t​e​d​ ​i​n​ ​t​h​i​s​ ​b​r​o​w​s​e​r​.​ ​P​l​e​a​s​e​ ​u​s​e​ ​t​h​e​ ​t​e​x​t​ ​i​n​p​u​t​ ​i​n​s​t​e​a​d​.
		 */
		voiceNotSupported: string
		/**
		 * L​i​s​t​e​n​i​n​g​…​ ​t​a​p​ ​t​o​ ​s​t​o​p
		 */
		listening: string
		/**
		 * T​a​p​ ​t​o​ ​s​t​a​r​t​ ​r​e​c​o​r​d​i​n​g
		 */
		tapToRecord: string
		/**
		 * C​o​u​l​d​ ​n​o​t​ ​a​c​c​e​s​s​ ​m​i​c​r​o​p​h​o​n​e​.
		 */
		micError: string
		/**
		 * A​n​a​l​y​s​e​ ​t​h​i​s​ ​m​e​a​l
		 */
		analyseThisMeal: string
		/**
		 * e​.​g​.​ ​C​h​i​c​k​e​n​ ​s​a​l​a​d
		 */
		mealNamePlaceholder: string
	}
	onboarding: {
		/**
		 * W​e​l​c​o​m​e​!
		 */
		welcomeTitle: string
		/**
		 * D​o​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​s​e​t​ ​u​p​ ​a​ ​d​a​i​l​y​ ​n​u​t​r​i​t​i​o​n​ ​g​o​a​l​?​ ​I​t​ ​o​n​l​y​ ​t​a​k​e​s​ ​a​ ​m​i​n​u​t​e​.
		 */
		welcomeDescription: string
		/**
		 * S​e​t​ ​u​p​ ​m​y​ ​g​o​a​l
		 */
		setupGoal: string
		/**
		 * S​k​i​p​ ​f​o​r​ ​n​o​w
		 */
		skipForNow: string
		/**
		 * H​o​w​ ​w​o​u​l​d​ ​y​o​u​ ​l​i​k​e​ ​t​o​ ​s​e​t​ ​y​o​u​r​ ​c​a​l​o​r​i​e​ ​t​a​r​g​e​t​?
		 */
		pathTitle: string
		/**
		 * G​u​i​d​e​ ​m​e​ ​t​h​r​o​u​g​h​ ​i​t
		 */
		pathGuideTitle: string
		/**
		 * W​e​'​l​l​ ​c​a​l​c​u​l​a​t​e​ ​y​o​u​r​ ​t​a​r​g​e​t​ ​b​a​s​e​d​ ​o​n​ ​y​o​u​r​ ​s​t​a​t​s
		 */
		pathGuideDesc: string
		/**
		 * I​ ​k​n​o​w​ ​m​y​ ​n​u​m​b​e​r​s
		 */
		pathDirectTitle: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​c​a​l​o​r​i​e​ ​a​n​d​ ​m​a​c​r​o​ ​t​a​r​g​e​t​s​ ​d​i​r​e​c​t​l​y
		 */
		pathDirectDesc: string
		/**
		 * Y​o​u​r​ ​s​t​a​t​s
		 */
		bodyStatsTitle: string
		/**
		 * U​s​e​d​ ​t​o​ ​c​a​l​c​u​l​a​t​e​ ​y​o​u​r​ ​d​a​i​l​y​ ​e​n​e​r​g​y​ ​n​e​e​d​s
		 */
		bodyStatsSubtitle: string
		/**
		 * W​e​i​g​h​t
		 */
		weight: string
		/**
		 * H​e​i​g​h​t
		 */
		height: string
		/**
		 * A​g​e
		 */
		age: string
		/**
		 * S​e​x
		 */
		sex: string
		/**
		 * A​c​t​i​v​i​t​y​ ​l​e​v​e​l
		 */
		activityTitle: string
		/**
		 * H​o​w​ ​a​c​t​i​v​e​ ​a​r​e​ ​y​o​u​ ​o​n​ ​a​ ​t​y​p​i​c​a​l​ ​w​e​e​k​?
		 */
		activitySubtitle: string
		/**
		 * S​e​d​e​n​t​a​r​y
		 */
		activitySedentaryLabel: string
		/**
		 * L​i​t​t​l​e​ ​o​r​ ​n​o​ ​e​x​e​r​c​i​s​e
		 */
		activitySedentaryDesc: string
		/**
		 * L​i​g​h​t​l​y​ ​a​c​t​i​v​e
		 */
		activityLightlyLabel: string
		/**
		 * 1​–​3​ ​d​a​y​s​/​w​e​e​k
		 */
		activityLightlyDesc: string
		/**
		 * M​o​d​e​r​a​t​e​l​y​ ​a​c​t​i​v​e
		 */
		activityModeratelyLabel: string
		/**
		 * 3​–​5​ ​d​a​y​s​/​w​e​e​k
		 */
		activityModeratelyDesc: string
		/**
		 * V​e​r​y​ ​a​c​t​i​v​e
		 */
		activityVeryLabel: string
		/**
		 * 6​–​7​ ​d​a​y​s​/​w​e​e​k
		 */
		activityVeryDesc: string
		/**
		 * E​x​t​r​a​ ​a​c​t​i​v​e
		 */
		activityExtraLabel: string
		/**
		 * P​h​y​s​i​c​a​l​ ​j​o​b​ ​o​r​ ​2​×​ ​d​a​i​l​y​ ​t​r​a​i​n​i​n​g
		 */
		activityExtraDesc: string
		/**
		 * Y​o​u​r​ ​g​o​a​l
		 */
		weightGoalTitle: string
		/**
		 * W​h​a​t​ ​a​r​e​ ​y​o​u​ ​t​r​y​i​n​g​ ​t​o​ ​a​c​h​i​e​v​e​?
		 */
		weightGoalSubtitle: string
		/**
		 * L​o​s​e​ ​w​e​i​g​h​t
		 */
		loseWeight: string
		/**
		 * 5​0​0​ ​k​c​a​l​ ​b​e​l​o​w​ ​y​o​u​r​ ​m​a​i​n​t​e​n​a​n​c​e​ ​l​e​v​e​l
		 */
		loseWeightDesc: string
		/**
		 * M​a​i​n​t​a​i​n​ ​w​e​i​g​h​t
		 */
		maintainWeight: string
		/**
		 * S​t​a​y​ ​a​t​ ​y​o​u​r​ ​m​a​i​n​t​e​n​a​n​c​e​ ​c​a​l​o​r​i​e​ ​l​e​v​e​l
		 */
		maintainWeightDesc: string
		/**
		 * G​a​i​n​ ​w​e​i​g​h​t
		 */
		gainWeight: string
		/**
		 * 5​0​0​ ​k​c​a​l​ ​a​b​o​v​e​ ​y​o​u​r​ ​m​a​i​n​t​e​n​a​n​c​e​ ​l​e​v​e​l
		 */
		gainWeightDesc: string
		/**
		 * Y​o​u​r​ ​d​a​i​l​y​ ​g​o​a​l​s
		 */
		reviewTitle: string
		/**
		 * C​a​l​c​u​l​a​t​e​d​ ​f​r​o​m​ ​y​o​u​r​ ​s​t​a​t​s​.​ ​F​e​e​l​ ​f​r​e​e​ ​t​o​ ​a​d​j​u​s​t​.
		 */
		reviewSubtitle: string
		/**
		 * M​a​i​n​t​e​n​a​n​c​e​ ​c​a​l​o​r​i​e​s​ ​(​T​D​E​E​)
		 */
		tdeeLabel: string
		/**
		 * W​h​a​t​ ​i​s​ ​T​D​E​E​?
		 */
		tdeeAriaLabel: string
		/**
		 * T​D​E​E​ ​(​T​o​t​a​l​ ​D​a​i​l​y​ ​E​n​e​r​g​y​ ​E​x​p​e​n​d​i​t​u​r​e​)​ ​i​s​ ​t​h​e​ ​n​u​m​b​e​r​ ​o​f​ ​c​a​l​o​r​i​e​s​ ​y​o​u​r​ ​b​o​d​y​ ​b​u​r​n​s​ ​i​n​ ​a​ ​d​a​y​.​ ​E​a​t​i​n​g​ ​a​t​ ​t​h​i​s​ ​l​e​v​e​l​ ​k​e​e​p​s​ ​y​o​u​r​ ​w​e​i​g​h​t​ ​s​t​a​b​l​e​.​ ​T​o​ ​l​o​s​e​ ​w​e​i​g​h​t​,​ ​y​o​u​r​ ​c​a​l​o​r​i​e​ ​g​o​a​l​ ​i​s​ ​s​e​t​ ​5​0​0​ ​k​c​a​l​ ​b​e​l​o​w​ ​y​o​u​r​ ​T​D​E​E​.
		 */
		tdeeExplainLose: string
		/**
		 * T​D​E​E​ ​(​T​o​t​a​l​ ​D​a​i​l​y​ ​E​n​e​r​g​y​ ​E​x​p​e​n​d​i​t​u​r​e​)​ ​i​s​ ​t​h​e​ ​n​u​m​b​e​r​ ​o​f​ ​c​a​l​o​r​i​e​s​ ​y​o​u​r​ ​b​o​d​y​ ​b​u​r​n​s​ ​i​n​ ​a​ ​d​a​y​.​ ​E​a​t​i​n​g​ ​a​t​ ​t​h​i​s​ ​l​e​v​e​l​ ​k​e​e​p​s​ ​y​o​u​r​ ​w​e​i​g​h​t​ ​s​t​a​b​l​e​.​ ​T​o​ ​g​a​i​n​ ​w​e​i​g​h​t​,​ ​y​o​u​r​ ​c​a​l​o​r​i​e​ ​g​o​a​l​ ​i​s​ ​s​e​t​ ​5​0​0​ ​k​c​a​l​ ​a​b​o​v​e​ ​y​o​u​r​ ​T​D​E​E​.
		 */
		tdeeExplainGain: string
		/**
		 * S​a​v​i​n​g​…
		 */
		reviewSaving: string
		/**
		 * S​a​v​e​ ​&​ ​c​o​n​t​i​n​u​e
		 */
		reviewSave: string
		/**
		 * Y​o​u​r​ ​d​a​i​l​y​ ​g​o​a​l​s
		 */
		directTitle: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​c​a​l​o​r​i​e​ ​a​n​d​ ​m​a​c​r​o​ ​t​a​r​g​e​t​s​.
		 */
		directSubtitle: string
		/**
		 * S​a​v​i​n​g​…
		 */
		directSaving: string
		/**
		 * S​a​v​e​ ​&​ ​c​o​n​t​i​n​u​e
		 */
		directSave: string
		/**
		 * 2​0​0​0
		 */
		caloriesPlaceholder: string
		/**
		 * 1​5​0
		 */
		proteinPlaceholder: string
		/**
		 * 2​0​0
		 */
		carbsPlaceholder: string
		/**
		 * 6​5
		 */
		fatPlaceholder: string
	}
}

export type TranslationFunctions = {
	meta: {
		/**
		 * Calorie Tracker
		 */
		title: () => LocalizedString
		/**
		 * AI-assisted daily calorie and macro tracker
		 */
		description: () => LocalizedString
	}
	ui: {
		/**
		 * Close
		 */
		close: () => LocalizedString
	}
	nav: {
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * Stats
		 */
		stats: () => LocalizedString
		/**
		 * Add meal
		 */
		addMeal: () => LocalizedString
		/**
		 * Favorites
		 */
		favorites: () => LocalizedString
		/**
		 * Profile
		 */
		profile: () => LocalizedString
	}
	login: {
		/**
		 * Calorie Tracker
		 */
		title: () => LocalizedString
		/**
		 * Enter your email to receive a magic link
		 */
		subtitle: () => LocalizedString
		/**
		 * Email address
		 */
		emailLabel: () => LocalizedString
		/**
		 * you@example.com
		 */
		emailPlaceholder: () => LocalizedString
		/**
		 * Send magic link
		 */
		sendLink: () => LocalizedString
		/**
		 * Sending…
		 */
		sending: () => LocalizedString
		/**
		 * Check your inbox — we sent a magic link to
		 */
		checkInbox: () => LocalizedString
	}
	common: {
		/**
		 * kcal
		 */
		kcal: () => LocalizedString
		/**
		 * g
		 */
		g: () => LocalizedString
		/**
		 * Calories
		 */
		calories: () => LocalizedString
		/**
		 * Protein
		 */
		protein: () => LocalizedString
		/**
		 * Carbs
		 */
		carbs: () => LocalizedString
		/**
		 * Fat
		 */
		fat: () => LocalizedString
		/**
		 * Fats
		 */
		fats: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Continue
		 */
		'continue': () => LocalizedString
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Saving…
		 */
		saving: () => LocalizedString
		/**
		 * Male
		 */
		male: () => LocalizedString
		/**
		 * Female
		 */
		female: () => LocalizedString
		/**
		 * Other
		 */
		other: () => LocalizedString
		/**
		 * Breakfast
		 */
		breakfast: () => LocalizedString
		/**
		 * Lunch
		 */
		lunch: () => LocalizedString
		/**
		 * Dinner
		 */
		dinner: () => LocalizedString
		/**
		 * Snack
		 */
		snack: () => LocalizedString
		/**
		 * Snacks
		 */
		snacks: () => LocalizedString
	}
	dashboard: {
		/**
		 * Welcome back
		 */
		welcomeBack: () => LocalizedString
		/**
		 * Today's Meals
		 */
		todaysMeals: () => LocalizedString
		/**
		 * No meals logged yet — tap + to add one
		 */
		noMeals: () => LocalizedString
		/**
		 * Last 7 Days
		 */
		last7Days: () => LocalizedString
		/**
		 * Over
		 */
		over: () => LocalizedString
		/**
		 * Remaining
		 */
		remaining: () => LocalizedString
		/**
		 * Macros
		 */
		macros: () => LocalizedString
		/**
		 * / {goal} kcal
		 */
		calGoal: (arg: { goal: number }) => LocalizedString
		/**
		 * {consumed}g / {goal}g
		 */
		macroAmount: (arg: { consumed: number, goal: number }) => LocalizedString
		/**
		 * {goal} kcal
		 */
		goalLineLabel: (arg: { goal: number }) => LocalizedString
		/**
		 * 7-day calorie history line chart
		 */
		chartAriaLabel: () => LocalizedString
	}
	goals: {
		/**
		 * Daily Goals
		 */
		title: () => LocalizedString
		/**
		 * Save goals
		 */
		saveGoals: () => LocalizedString
		/**
		 * Open goal settings
		 */
		openSettings: () => LocalizedString
		/**
		 * Calories (kcal)
		 */
		caloriesKcal: () => LocalizedString
		/**
		 * Protein (g)
		 */
		proteinG: () => LocalizedString
		/**
		 * Carbs (g)
		 */
		carbsG: () => LocalizedString
		/**
		 * Fat (g)
		 */
		fatG: () => LocalizedString
		/**
		 * TDEE Calculator
		 */
		tdeeTitle: () => LocalizedString
		/**
		 * Calculates your Total Daily Energy Expenditure using the Mifflin-St Jeor formula and fills in your calorie goal.
		 */
		tdeeDescription: () => LocalizedString
		/**
		 * ▲ hide
		 */
		tdeeHide: () => LocalizedString
		/**
		 * ▼ show
		 */
		tdeeShow: () => LocalizedString
		/**
		 * Calculate & fill calorie goal
		 */
		calculateFill: () => LocalizedString
		/**
		 * Weight (kg)
		 */
		weightKg: () => LocalizedString
		/**
		 * Height (cm)
		 */
		heightCm: () => LocalizedString
		/**
		 * Age
		 */
		age: () => LocalizedString
		/**
		 * Sex
		 */
		sex: () => LocalizedString
		/**
		 * Select…
		 */
		selectPlaceholder: () => LocalizedString
		/**
		 * Activity level
		 */
		activityLevel: () => LocalizedString
		/**
		 * Sedentary (little/no exercise)
		 */
		activitySedentary: () => LocalizedString
		/**
		 * Lightly active (1–3 days/week)
		 */
		activityLightly: () => LocalizedString
		/**
		 * Moderately active (3–5 days/week)
		 */
		activityModerately: () => LocalizedString
		/**
		 * Very active (6–7 days/week)
		 */
		activityVery: () => LocalizedString
		/**
		 * Extra active (physical job)
		 */
		activityExtra: () => LocalizedString
	}
	addMeal: {
		/**
		 * Log a meal
		 */
		title: () => LocalizedString
		/**
		 * Review estimate
		 */
		reviewEstimate: () => LocalizedString
		/**
		 * Meal name
		 */
		mealName: () => LocalizedString
		/**
		 * Meal type
		 */
		mealType: () => LocalizedString
		/**
		 * AI Text
		 */
		tabText: () => LocalizedString
		/**
		 * AI Voice
		 */
		tabVoice: () => LocalizedString
		/**
		 * Manual
		 */
		tabManual: () => LocalizedString
		/**
		 * Describe what you ate… e.g. 'A bowl of pasta bolognese with parmesan and a glass of red wine'
		 */
		textPlaceholder: () => LocalizedString
		/**
		 * {count}/500
		 */
		charCount: (arg: { count: number }) => LocalizedString
		/**
		 * Analysing…
		 */
		analysing: () => LocalizedString
		/**
		 * Analyse
		 */
		analyse: () => LocalizedString
		/**
		 * Add meal
		 */
		addMeal: () => LocalizedString
		/**
		 * ⚠ Low confidence
		 */
		lowConfidence: () => LocalizedString
		/**
		 * Medium confidence
		 */
		mediumConfidence: () => LocalizedString
		/**
		 * Failed to parse meal. Please try again.
		 */
		failedToParse: () => LocalizedString
		/**
		 * Voice input is not supported in this browser. Please use the text input instead.
		 */
		voiceNotSupported: () => LocalizedString
		/**
		 * Listening… tap to stop
		 */
		listening: () => LocalizedString
		/**
		 * Tap to start recording
		 */
		tapToRecord: () => LocalizedString
		/**
		 * Could not access microphone.
		 */
		micError: () => LocalizedString
		/**
		 * Analyse this meal
		 */
		analyseThisMeal: () => LocalizedString
		/**
		 * e.g. Chicken salad
		 */
		mealNamePlaceholder: () => LocalizedString
	}
	onboarding: {
		/**
		 * Welcome!
		 */
		welcomeTitle: () => LocalizedString
		/**
		 * Do you want to set up a daily nutrition goal? It only takes a minute.
		 */
		welcomeDescription: () => LocalizedString
		/**
		 * Set up my goal
		 */
		setupGoal: () => LocalizedString
		/**
		 * Skip for now
		 */
		skipForNow: () => LocalizedString
		/**
		 * How would you like to set your calorie target?
		 */
		pathTitle: () => LocalizedString
		/**
		 * Guide me through it
		 */
		pathGuideTitle: () => LocalizedString
		/**
		 * We'll calculate your target based on your stats
		 */
		pathGuideDesc: () => LocalizedString
		/**
		 * I know my numbers
		 */
		pathDirectTitle: () => LocalizedString
		/**
		 * Enter your calorie and macro targets directly
		 */
		pathDirectDesc: () => LocalizedString
		/**
		 * Your stats
		 */
		bodyStatsTitle: () => LocalizedString
		/**
		 * Used to calculate your daily energy needs
		 */
		bodyStatsSubtitle: () => LocalizedString
		/**
		 * Weight
		 */
		weight: () => LocalizedString
		/**
		 * Height
		 */
		height: () => LocalizedString
		/**
		 * Age
		 */
		age: () => LocalizedString
		/**
		 * Sex
		 */
		sex: () => LocalizedString
		/**
		 * Activity level
		 */
		activityTitle: () => LocalizedString
		/**
		 * How active are you on a typical week?
		 */
		activitySubtitle: () => LocalizedString
		/**
		 * Sedentary
		 */
		activitySedentaryLabel: () => LocalizedString
		/**
		 * Little or no exercise
		 */
		activitySedentaryDesc: () => LocalizedString
		/**
		 * Lightly active
		 */
		activityLightlyLabel: () => LocalizedString
		/**
		 * 1–3 days/week
		 */
		activityLightlyDesc: () => LocalizedString
		/**
		 * Moderately active
		 */
		activityModeratelyLabel: () => LocalizedString
		/**
		 * 3–5 days/week
		 */
		activityModeratelyDesc: () => LocalizedString
		/**
		 * Very active
		 */
		activityVeryLabel: () => LocalizedString
		/**
		 * 6–7 days/week
		 */
		activityVeryDesc: () => LocalizedString
		/**
		 * Extra active
		 */
		activityExtraLabel: () => LocalizedString
		/**
		 * Physical job or 2× daily training
		 */
		activityExtraDesc: () => LocalizedString
		/**
		 * Your goal
		 */
		weightGoalTitle: () => LocalizedString
		/**
		 * What are you trying to achieve?
		 */
		weightGoalSubtitle: () => LocalizedString
		/**
		 * Lose weight
		 */
		loseWeight: () => LocalizedString
		/**
		 * 500 kcal below your maintenance level
		 */
		loseWeightDesc: () => LocalizedString
		/**
		 * Maintain weight
		 */
		maintainWeight: () => LocalizedString
		/**
		 * Stay at your maintenance calorie level
		 */
		maintainWeightDesc: () => LocalizedString
		/**
		 * Gain weight
		 */
		gainWeight: () => LocalizedString
		/**
		 * 500 kcal above your maintenance level
		 */
		gainWeightDesc: () => LocalizedString
		/**
		 * Your daily goals
		 */
		reviewTitle: () => LocalizedString
		/**
		 * Calculated from your stats. Feel free to adjust.
		 */
		reviewSubtitle: () => LocalizedString
		/**
		 * Maintenance calories (TDEE)
		 */
		tdeeLabel: () => LocalizedString
		/**
		 * What is TDEE?
		 */
		tdeeAriaLabel: () => LocalizedString
		/**
		 * TDEE (Total Daily Energy Expenditure) is the number of calories your body burns in a day. Eating at this level keeps your weight stable. To lose weight, your calorie goal is set 500 kcal below your TDEE.
		 */
		tdeeExplainLose: () => LocalizedString
		/**
		 * TDEE (Total Daily Energy Expenditure) is the number of calories your body burns in a day. Eating at this level keeps your weight stable. To gain weight, your calorie goal is set 500 kcal above your TDEE.
		 */
		tdeeExplainGain: () => LocalizedString
		/**
		 * Saving…
		 */
		reviewSaving: () => LocalizedString
		/**
		 * Save & continue
		 */
		reviewSave: () => LocalizedString
		/**
		 * Your daily goals
		 */
		directTitle: () => LocalizedString
		/**
		 * Enter your calorie and macro targets.
		 */
		directSubtitle: () => LocalizedString
		/**
		 * Saving…
		 */
		directSaving: () => LocalizedString
		/**
		 * Save & continue
		 */
		directSave: () => LocalizedString
		/**
		 * 2000
		 */
		caloriesPlaceholder: () => LocalizedString
		/**
		 * 150
		 */
		proteinPlaceholder: () => LocalizedString
		/**
		 * 200
		 */
		carbsPlaceholder: () => LocalizedString
		/**
		 * 65
		 */
		fatPlaceholder: () => LocalizedString
	}
}

export type Formatters = {}
